# src/build.yml
---
build: RELEASE
version: latest
---
ACPI:
  SSDT-ChromeKeys: "ACPI/SSDT-ChromeKeys.dsl"
  SSDT-Devices: "ACPI/SSDT-Devices.dsl"
  SSDT-EC-USBX: "ACPI/SSDT-EC-USBX.dsl"
  SSDT-Fake-ALS: "ACPI/SSDT-Fake-ALS.dsl"
  SSDT-I2C: "ACPI/SSDT-I2C.dsl"
  SSDT-PLUG-ALT: "ACPI/SSDT-PLUG-ALT.dsl"
  SSDT-PNLF: "ACPI/SSDT-PNLF.dsl"
Drivers:
  - HfsPlus
  - OpenRuntime
  - OpenCanopy
  - OpenLinuxBoot
Kexts:
  Lilu: latest
  WhateverGreen: latest

  # VirtualSMC + plugins
  VirtualSMC:
    specifier: latest
  SMCBatteryManager: "*"
  SMCProcessor: "*"
  ECEnabler: 1Revenger1/ECEnabler=latest
  NVMeFix: latest

  # Wifi
  AirportItlwm-Sonoma14.4:
    specifier: OpenIntelWireless/itlwm=^2.2.0
    MaxKernel: "23.99.99"
    MinKernel: "23.4.0"
  AirportItlwm-Catalina:
    specifier: OpenIntelWireless/itlwm=^2.2.0
    MaxKernel: "19.99.99"
    MinKernel: "19.0.0"
  
  # Bluetooth
  BlueToolFixup:
    specifier: acidanthera/BrcmPatchRAM=latest
    MinKernel: "21.00.0"
  IntelBTPatcher: OpenIntelWireless/IntelBluetoothFirmware=latest
  IntelBluetoothFirmware: "*"
  IntelBluetoothInjector:
    specifier: "*"
    MaxKernel: "20.99.9"

  # Input
  VoodooI2C:
    specifier: VoodooI2C/VoodooI2C=^2.9.1
    bundled:
      - VoodooI2CServices
      - VoodooGPIO
      - VoodooInput
  VoodooI2CHID: "*"
  VoodooI2CELAN: "*"
  
  KledTouchscreen: "./Kexts/KledTouchscreen.kext"
  
  # PS/2 Keyboard
  VoodooPS2Controller:
    specifier: 1Revenger1/VoodooPS2=^3.0.1
    bundled:
      - VoodooPS2Keyboard

  # Fan control
  ChultraDPTF: "./Kexts/ChultraDPTF.kext"
  # Accelorometer and Chromebook specific controls
  CrosEC: 1Revenger1/CrosEC=latest

Resources:
Tools:
  - OpenShell
  - MmapDump
