
# ==============================================================================
# |                            Touchscreen Fixes                               |
# ==============================================================================

# The touchscreen requires interrupts to be routed through the GPIO controller
# instead of the APIC, as the APIC vector is above macOS's max of 0x2F. This
# is done in SSDT-I2C, which redefines the _CRS method.
ACPI:
  @override
  Patch:
    - Comment:                        String  | "Touchscreen - Rename _CRS to XCRS"
      Find:                           Data    | <5F435253>
      Replace:                        Data    | <58435253>
      Count:                          Number  | 1
  @override
  Delete:                             Array   | []

# ==============================================================================
# |                         Firmware/Memory Map Fixes                          |
# ==============================================================================

Booter:
  Quirks:
    SetupVirtualMap:                  Boolean | true
    # Prevents kernel panic on `Invalid frame pointer`.
    # - https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#kernel-panic-on-invalid-frame-pointer
    # - Note: The below options reflect support for MATs (2018+ firmware).
    EnableWriteUnprotector:           Boolean | false
    ProtectUefiServices:              Boolean | true
    RebuildAppleMemoryMap:            Boolean | true
    SyncRuntimePermissions:           Boolean | true
    # Keep custom slide enabled as not all slides are usable.
    EnableSafeModeSlide:              Boolean | true
    ProvideCustomSlide:               Boolean | true
  @override
  MmioWhitelist:                      Array   | []
  @override
  Patch:                              Array   | []

Kernel:
  Quirks:
    # Ignore CFG Lock/MSR 0x2E
    AppleXcpmCfgLock:                 Boolean | true

# ==============================================================================
# |                      Hibernation and NVRAM Fixes                           |
# ==============================================================================

# Fixes NVRAM and other EFI runtime services
Booter:
  Quirks:
    ProtectMemoryRegions:             Boolean | true
    # The firmware only has one 256k region with runtime attributes.
    # We disable this instead of adding an MMIO region.
    DevirtualiseMmio:     Boolean | false

# NVMe Device Properties
# macOS will not hibernate unless the NVMe is marked as internal
DeviceProperties:
  Add:
    PciRoot(0x0)/Pci(0x1D,0x0)/Pci(0x0,0x0):
      built-in:                       Data    | <01000000>

# Tell OpenCore to look for either RTC or NVRAM hibernation variables
Misc:
  Boot:
    HibernateMode                     String  | "Auto"
    HibernationSkipsPicker            Boolean | True

# Protect memory region at 0x8B000 required for hibernation
UEFI:
  @override
  ReservedMemory:
    - Comment:                        String  | "Fix black screen on wake from hibernation"
      Address:                        Number  | 569344
      Enabled:                        Boolean | True
      Size:                           Number  | 4096
      Type:                           String  | "RuntimeCode"

# ==============================================================================
# |                                iGPU Fixes                                  |
# ==============================================================================

DeviceProperties:
  @override
  Add:
    # iGPU Device Properties
    PciRoot(0x0)/Pci(0x2,0x0):
      AAPL,ig-platform-id:            Data    | <00009B3E>
      # Spoof as UHD 630
      device-id:                      Data    | <9B3E0000>
      # Coreboot specific fix
      disable-telemetry-load:         Data    | <01000000>
      # Backlight fixes
      enable-backlight-registers-fix: Data    | <01000000>
      enable-backlight-registers-alternative-fix: Data | <01000000>
      enable-backlight-smoother:      Data    | <01000000>

# ==============================================================================
# |                            Debug Boot-args                                 |
# ==============================================================================

NVRAM:
  @override
  Add:
    7C436110-AB2A-4BBB-A880-FE41995C9F82:
      boot-args:                      String | "-v keepsyms=1 debug=0x100 msgbuf=1048576"
  @override
  Delete:
    7C436110-AB2A-4BBB-A880-FE41995C9F82:
      - boot-args
  
  # Only used when using emulated NVRAM
  @override
  LegacySchema:                       Dictionary | {}

Kernel:
  Quirks:
    # Remove kext list dump when panic occurs
    PanicNoKextDump:                  Boolean | true
    # Prevent timeout kernel panics
    PowerTimeoutKernelPanic:          Boolean | true
  
  # Unused fields
  @override
  Block:                              Array   | []
  @override
  Force:                              Array   | []
  @override
  Patch:                              Array   | []

# ==============================================================================
# |                             OpenCore Picker                                |
# ==============================================================================

Misc:
  Boot:
    Timeout:                          Number  | 5
    # Hide recovery and other extra entries unless Spacebar is pressed
    HideAuxiliary:                    Boolean | True
    # Picker attributes for OpenCanopy
    # 1 = Use Custom Volume icons
    # 2 = Use disk label files
    # 16 = Pointer support
    # 128 = Use Flavour Icons
    PickerAttributes:                 Number  | 147
    # Use OpenCanopy instead of builtin picker
    PickerMode:                       String  | "External"
    # Allows all partitions to show
    ScanPolicy:                       Number  | 0

# ==============================================================================
#                         Vaulting and Apple Secure Boot                       |
# ==============================================================================

Misc:
  Security:
    # Apple Secure Boot hardware model
    # Left as default since the model we emulate has a T2 chip
    # - https://dortania.github.io/OpenCore-Post-Install/universal/security/applesecureboot.html#securebootmodel
    SecureBootModel:                  String  | "Default"
    # OpenCore vaulting configuration
    # - https://dortania.github.io/OpenCore-Post-Install/universal/security/vault.html
    Vault:                            String  | "Optional"

NVRAM:
  Add:
    7C436110-AB2A-4BBB-A880-FE41995C9F82:
      # Enables System Integrity Protection (SIP) setting in macOS.
      # - https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/post-issues.html#disabling-sip
      csr-active-config:              Data    | <00000000>

# Set the allowed minimum APFS version to the one provided by macOS Catalina
UEFI:
  APFS:
    MinDate:                          Number  | 20200306
    MinVersion:                       Number  | 1412101001000000